version: '3.9'

services:
  app:
    container_name: postinscripciones
    build: .
    restart: always
    env_file: .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
    links:
      - db
  db:
    image: "mysql:8.0"
    restart: always
    container_name: postinscripciones_db
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
volumes:
  mysql-volume :
