version: '3.9'

services:
  app:
    container_name: postinscripciones_app
    build:
      context: .
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
    links:
      - db
  db:
    image: "mysql:8.0"
    restart: always
    container_name: postinscripciones_db
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db-data-volume:/var/lib/mysql-data
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
volumes:
  db-data-volume:
